include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_specify_types: true # 명시적 타입 지정
    avoid_classes_with_only_static_members: true # 유틸 함수 전역으로 설정
    avoid_escaping_inner_quotes: true # String 타입에서는 "" 사용
    avoid_multiple_declarations_per_line: true # 한 줄에 한 개의 변수만 선언
    avoid_unnecessary_containers: true # 불필요한 컨테이너 사용 방지
    avoid_unused_constructor_parameters: true # 생성자 파라미터 체크
    camel_case_types: true # UpperCamelCase
    constant_identifier_names: true # LowerCamelCase (상수)
    curly_braces_in_flow_control_structures: true # 한 줄 이하인 if문 중괄호 생략 방지
    non_constant_identifier_names: true # LowerCamelCase (식별자)
    unnecessary_async: true # 불필요한 비동기 방지
    unnecessary_const: true # 불필요한 const 방지
    unnecessary_parenthesis: true # 불필요한 괄호 방지
    use_named_constants: true # 미리 정의된 상수값 사용
    valid_regexps: true # 유효한 정규식 체크
    prefer_const_constructors: true # 클래스의 생성자에서 const 사용 체크
    prefer_const_constructors_in_immutables: true # @immutable 클래스의 생성자에서 const 사용 체크를 위함
    prefer_const_literals_to_create_immutables: true # @immutable 클래스의 생성자의 리터럴 파라미터에서 const 사용 체크를 위함
