name: mango
description: "냉장고 물품 관리 및 '전국통합식품영양성분정보표준데이터'API를 활용한 토이 프로젝트"
publish_to: 'none'

version: 1.1.3+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sign_in_with_apple: ^6.1.4
  kakao_flutter_sdk: ^1.9.6
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.2
  webview_flutter: ^4.9.0
  go_router: ^14.8.1
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.12
  freezed_annotation: ^3.0.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  package_info_plus: ^8.3.0
  shimmer: ^3.0.0
  custom_sliding_segmented_control: ^1.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  retrofit_generator:
  build_runner: ^2.4.15
  freezed: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/title.png
    - assets/images/cart.png
    - assets/images/null_home.png
    - assets/images/null_cook.png
    - assets/images/null_item.png

  fonts:
    - family: Mainfonts
      fonts:
        - asset: assets/fonts/GangwonLight.ttf # 기본
        - asset: assets/fonts/GangwonBold.ttf
          weight: 700
