import 'package:mango/model/content.dart';

class ContentRepository {
  // content 저장 함수
  Future<void> saveContent(Content content) async {
    await Future.delayed(Duration(seconds: 1));
  }

  // groupId로 content list 불러오는 함수
  Future<List<Content>> loadContentList(String groupId) async {
    // groupId 해당하는 content list 불러오는 api 호출
    await Future.delayed(Duration(seconds: 1));

    return <Content>[
      // 냉장
      Content(
        contentId: 'i00000001',
        contentName: '코카콜라',
        category: '냉장',
        count: 5,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-22 18:55:22'),
        storageArea: '냉장',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000002',
        contentName: '토마토 케찹',
        category: '냉장',
        count: 3,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-23 18:55:22'),
        storageArea: '냉장',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000003',
        contentName: '냉장보관 하는 과일',
        category: '냉장',
        count: 2,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-22 18:55:22'),
        storageArea: '냉장',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000004',
        contentName: '치즈',
        category: '냉장',
        count: 4,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-24 18:55:22'),
        storageArea: '냉장',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000005',
        contentName: '스팸',
        category: '냉장',
        count: 3,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-21 18:55:22'),
        storageArea: '냉장',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),

      // 냉동
      Content(
        contentId: 'i00000006',
        contentName: '냉동 삼겹살',
        category: '냉동',
        count: 5,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-21 18:55:22'),
        storageArea: '냉동',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000007',
        contentName: '구슬 아이스크림',
        category: '냉동',
        count: 3,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-23 18:55:22'),
        storageArea: '냉동',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000008',
        contentName: '냉동 오징어',
        category: '냉동',
        count: 4,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-22 18:55:22'),
        storageArea: '냉동',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000009',
        contentName: '냉동 치킨',
        category: '냉동',
        count: 2,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-22 18:55:22'),
        storageArea: '냉동',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000010',
        contentName: '냉동 쌀밥',
        category: '냉동',
        count: 5,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-21 18:55:22'),
        storageArea: '냉동',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000011',
        contentName: '아이스크림',
        category: '냉동',
        count: 3,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-23 18:55:22'),
        storageArea: '냉동',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000012',
        contentName: '냉동 족발',
        category: '냉동',
        count: 7,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-22 18:55:22'),
        storageArea: '냉동',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
      Content(
        contentId: 'i00000013',
        contentName: '냉동 순대',
        category: '냉동',
        count: 5,
        regDate: DateTime.now(),
        expDate: DateTime.parse('2025-01-20 18:55:22'),
        storageArea: '냉동',
        memo: '',
        nutriUnit: '',
        nutriCapacity: 0,
        nutriKcal: 0,
        nutriCarbohydrate: 0,
        nutriProtein: 0,
        nutriFat: 0,
      ),
    ];
  }
}
