import 'package:mango/model/refrigerator_item.dart';

class ItemRepository {
  // 검색어를 받아오면 해당 검색어에 해당하는 결과 리스트 받아오는 api 함수
  Future<List<RefrigeratorItem>> loadItemListByString(String searchTerm) async {
    await Future.delayed(Duration(seconds: 1));
    return <RefrigeratorItem>[
      RefrigeratorItem(
        groupId: "g00000001",
        isOpenItem: true,
        itemName: "소고기",
        category: "육류",
        brandName: "한우",
        count: 2,
        regDate: DateTime.parse("2025-03-10 14:30:00"),
        expDate: DateTime.parse("2025-03-15 23:59:59"),
        storageArea: "냉장",
        memo: "불고기용",
        nutriUnit: "g",
        nutriCapacity: 200,
        nutriKcal: 250,
        nutriCarbohydrate: 10,
        nutriProtein: 20,
        nutriFat: 18,
      ),
      RefrigeratorItem(
        groupId: "g00000002",
        isOpenItem: true,
        itemName: "콜라",
        category: "음료류",
        brandName: "코카콜라",
        count: 3,
        regDate: DateTime.parse("2025-03-08 12:45:10"),
        expDate: DateTime.parse("2025-06-08 23:59:59"),
        storageArea: "냉장",
        memo: "제로콜라",
        nutriUnit: "ml",
        nutriCapacity: 250,
        nutriKcal: 10,
        nutriCarbohydrate: 10,
        nutriProtein: 10,
        nutriFat: 10,
      ),
      RefrigeratorItem(
        groupId: "g00000003",
        isOpenItem: true,
        itemName: "당근",
        category: "채소류",
        brandName: "국내산",
        count: 5,
        regDate: DateTime.parse("2025-03-09 10:00:00"),
        expDate: DateTime.parse("2025-03-20 23:59:59"),
        storageArea: "냉장",
        memo: "볶음용",
        nutriUnit: "g",
        nutriCapacity: 100,
        nutriKcal: 41,
        nutriCarbohydrate: 10,
        nutriProtein: 1,
        nutriFat: 10,
      ),
      RefrigeratorItem(
        groupId: "g00000004",
        isOpenItem: true,
        itemName: "초코과자",
        category: "과자류",
        brandName: "오리온",
        count: 1,
        regDate: DateTime.parse("2025-03-05 16:20:30"),
        expDate: DateTime.parse("2025-05-05 23:59:59"),
        storageArea: "냉동",
        memo: "달콤한 간식",
        nutriUnit: "g",
        nutriCapacity: 50,
        nutriKcal: 250,
        nutriCarbohydrate: 30,
        nutriProtein: 3,
        nutriFat: 12,
      ),
      RefrigeratorItem(
        groupId: "g00000005",
        isOpenItem: true,
        itemName: "바닐라 아이스크림",
        category: "아이스크림류",
        brandName: "베스킨라빈스",
        count: 2,
        regDate: DateTime.parse("2025-03-07 19:15:00"),
        expDate: DateTime.parse("2025-09-07 23:59:59"),
        storageArea: "냉동",
        memo: "디저트",
        nutriUnit: "g",
        nutriCapacity: 150,
        nutriKcal: 200,
        nutriCarbohydrate: 20,
        nutriProtein: 4,
        nutriFat: 10,
      ),
    ];
  }
}
