import 'package:mango/model/content.dart';

List<Content> sampleContentList = [
  Content(
    contentId: 1,
    contentName: "사과",
    category: "과일",
    count: 3,
    regDate: DateTime(2025, 3, 1),
    expDate: DateTime(2025, 3, 10),
    storageArea: "냉장",
    memo: "신선한 사과",
    nutriUnit: "g",
    nutriCapacity: 100,
    nutriKcal: 52,
    nutriCarbohydrate: 14,
    nutriProtein: 0,
    nutriFat: 0,
  ),
  Content(
    contentId: 2,
    contentName: "닭가슴살",
    category: "육류",
    count: 0,
    regDate: DateTime(2025, 3, 2),
    expDate: DateTime(2025, 3, 20),
    storageArea: "냉동",
    memo: "운동용",
    nutriUnit: "g",
    nutriCapacity: 100,
    nutriKcal: 165,
    nutriCarbohydrate: 0,
    nutriProtein: 31,
    nutriFat: 3,
  ),
  Content(
    contentId: 3,
    contentName: "양파",
    category: "채소",
    count: 2,
    regDate: DateTime(2025, 3, 3),
    expDate: DateTime(2025, 3, 15),
    storageArea: "실온",
    memo: "국 끓일 때 사용",
    nutriUnit: "g",
    nutriCapacity: 100,
    nutriKcal: 40,
    nutriCarbohydrate: 9,
    nutriProtein: 1,
    nutriFat: 0,
  ),
  Content(
    contentId: 4,
    contentName: "쌀",
    category: "곡물",
    count: 10,
    regDate: DateTime(2025, 2, 25),
    expDate: DateTime(2025, 12, 31),
    storageArea: "실온",
    memo: "밥 짓는 용도",
    nutriUnit: "g",
    nutriCapacity: 100,
    nutriKcal: 130,
    nutriCarbohydrate: 28,
    nutriProtein: 2,
    nutriFat: 0,
  ),
  Content(
    contentId: 5,
    contentName: "우유",
    category: "유제품",
    count: 1,
    regDate: DateTime(2025, 3, 5),
    expDate: DateTime(2025, 3, 12),
    storageArea: "냉장",
    memo: "아침에 마시기",
    nutriUnit: "ml",
    nutriCapacity: 200,
    nutriKcal: 122,
    nutriCarbohydrate: 12,
    nutriProtein: 8,
    nutriFat: 5,
  ),
];
